[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chrono = "0.4.39"
sea-orm = { version = "1.1.4", features = ["chrono"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
schemars = "0.8.22"
